# Generated by Django 6.0 on 2025-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
